language: python

python:
  - 3.5.2

install:
  - pip install -r requirements.txt
  - pip install git+https://github.com/thtrieu/darkflow
  - pip install pytest-cov
  - pip install codecov
  # Test data
  - wget aberturasdalum.com.ar:8080/trafficsigns.weights -O data/yolo/full/trafficsigns.weights
  - mkdir tests/data
  - wget http://www.educacionsantacruz.gov.ar/images/Educ_Ambiental/Monte_Leon/PNMonteLeon/imagenes/ruta.jpg -O tests/data/test.jpg

script:
  - pytest --cov=./

after_success:
  - codecov
