language: python

python:
  - 3.5.2

install:
  # Dependencies
  - pip install -r requirements.txt
  - pip install git+https://github.com/thtrieu/darkflow
  - pip install pytest-cov
  - pip install codecov
  # Test Data
  - mkdir tests/data
  - wget http://www.educacionsantacruz.gov.ar/images/Educ_Ambiental/Monte_Leon/PNMonteLeon/imagenes/ruta.jpg -O tests/data/test.jpg
  # Initialize detector
  - make init
  # Classifier Test Data
  - wget http://aberturasdalum.com.ar:8080/test_sq.png -O ./tests/data/test_sq.png
  # Localizer Test Data
  - wget http://aberturasdalum.com.ar:8080/test.png -O ./tests/data/test.png
  # Detector Test Data
  - wget http://aberturasdalum.com.ar:8080/test.mp4 -O ./tests/data/test.mp4

script:
  - pytest --cov=./

after_success:
  - codecov
