language: python

python:
  - 3.5.2

install:
  - pip install -r requirements.txt
  #- pip install coveralls

script:
  - pytest
  #- coverage run --source=gestion manage.py test gestion

after_success:
  #- coveralls
