language: python

python:
  - 3.5.2

install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install coveralls

script:
  - pytest --cov=coverage tests/

after_success:
  - coveralls
